Repository NVIDIA-NeMo/RL, pull requests merged in 2025-09, with the labels that each got.

#724 feat: Overlong filtering for GRPO
  docs/guides/grpo.md
  examples/configs/grpo_math_1B.yaml
  examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-gspo-deepscaler-1.5b-8K.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-2n8g-fsdp2tp1-noncolocated.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-megatron.yaml
  examples/configs/recipes/llm/grpo-math-qwen3-30ba3b-megatron-tp4-32k.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-megatron.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/recipes/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/vlm_grpo_3B.yaml
  nemo_rl/algorithms/grpo.py
  nemo_rl/experience/rollouts.py
Labels: documentation, community-request

#1047 ci: Only run build-test-publish-wheel workflow if env var set
  .github/workflows/build-test-publish-wheel.yml
Labels: CI

#1056 feat: add testmon support to detect when tests need to be rerun
  .gitignore
  docs/testing.md
  nemo_rl/distributed/virtual_cluster.py
  pyproject.toml
  tests/unit/__init__.py
  tests/unit/_plugins/remote_select.py
  uv.lock
Labels: documentation

#1074 fix: optional clear cache between microbatch iterations
  examples/configs/dpo.yaml
  examples/configs/recipes/llm/dpo-mistral-nemo-instruct-2407-1n8g-fsdp2tp8-actckpt-long.yaml
  nemo_rl/models/policy/__init__.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/dtensor_policy_worker_v2.py
Labels: CI:L1

#1014 fix: convergence issue by adding use_inductor=False in vllm compilation_config
  docs/adding-new-models.md
  examples/configs/grpo_math_1B.yaml
  examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml
  nemo_rl/models/generation/vllm/vllm_worker_async.py
  pyrefly.toml
  tests/unit/test_recipes_and_test_suites.py
  tools/model_diagnostics/4.vllm_precision_compilation_test.py
Labels: documentation

#1034 fix: report the correct number of workers during FLOPs calculation
  nemo_rl/models/policy/lm_policy.py
  nemo_rl/utils/flops_formulas.py
  nemo_rl/utils/flops_tracker.py
  tests/unit/models/policy/test_dtensor_worker.py
  tests/unit/models/policy/test_megatron_worker.py
  tests/unit/utils/test_flops_counter.py
Labels: CI:L1

#1106 docs: update `grpo.md`
  docs/guides/grpo.md
Labels: documentation

#1148 ci: Remove test comment from automodel integration check
  .github/workflows/_automodel_integration_check.yml
Labels: CI

#1133 chore: introduce codeowners
  .github/CODEOWNERS
  nemo_rl/converters/__init__.py
  nemo_rl/converters/huggingface/__init__.py
  nemo_rl/converters/huggingface/vllm_export.py
  nemo_rl/converters/megatron/__init__.py
  nemo_rl/converters/megatron/vllm_export.py
  nemo_rl/metrics/__init__.py
  nemo_rl/metrics/metrics_utils.py
  pyrefly.toml
Labels: CI

#1111 ci: Add merge queue retry if CI_TIMEOUT
  .github/workflows/merge-queue-retry.yml
Labels: CI

#1136 chore: add deepep install instruction
  README.md
  pyproject.toml
Labels: CI:docs, r0.4.0

#1167 feat: add support for COMMAND= in ray.sub *-attach.sh scripts
  ray.sub
Labels: CI:docs

#1105 fix: cleaned up the instructions around installing cuDNN
  README.md
Labels: CI:docs, r0.4.0

#1172 ci: Run nightly Github tests
  .github/workflows/cicd-main.yml
Labels: CI, CI:docs

#1174 ci: Set HF_HUB_OFFLINE=1 during tests when PR is from a fork
  .github/actions/test-template/action.yml
  .github/workflows/cicd-main.yml
Labels: CI, CI:docs

#1098 feat: add async RL support
  docs/guides/async-grpo.md
  docs/index.md
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_math_1B_megatron.yaml
  examples/configs/grpo_math_8B.yaml
  examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-8n8g-fsdp2tp8-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-gspo-deepscaler-1.5b-8K.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-2n8g-fsdp2tp1-noncolocated.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-megatron.yaml
  examples/configs/recipes/llm/grpo-math-qwen3-30ba3b-megatron-tp4-32k.yaml
  examples/configs/recipes/llm/grpo-moonlight-16ba3b-4n8g-megatron.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-megatron.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/recipes/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/vlm_grpo_3B.yaml
  examples/run_grpo_math.py
  nemo_rl/algorithms/async_utils.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/distributed/ray_actor_environment_registry.py
  tests/functional/L1_Functional_Tests_GPU.sh
  tests/functional/grpo_async.sh
  tests/unit/algorithms/test_async_utils.py
Labels: documentation, CI:L1, r0.4.0

#1143 perf: Add a field in SFT data config to modify num_workers for loading data
  examples/configs/sft.yaml
  nemo_rl/algorithms/sft.py
  nemo_rl/data/__init__.py
Labels: CI:L1, r0.4.0

#1168 fix: Run crash on get_latest_checkpoint
  nemo_rl/utils/checkpoint.py
  tests/unit/utils/test_checkpoint.py
Labels: CI:L1, r0.4.0

#876 chore: patch KL loss to prevent nans
  nemo_rl/algorithms/utils.py
Labels: r0.4.0

#923 feat: support swanlab logger
  docs/design-docs/logger.md
  examples/configs/dpo.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_math_1B_megatron.yaml
  examples/configs/grpo_sliding_puzzle.yaml
  examples/configs/rm.yaml
  examples/configs/sft.yaml
  examples/configs/sft_openmathinstruct2.yaml
  examples/configs/vlm_grpo_3B.yaml
  nemo_rl/utils/logger.py
  pyproject.toml
  tests/unit/utils/test_logger.py
  uv.lock
Labels: documentation, CI:L1

#1192 ci: Add status badge and prevent merging if no tests ran
  .github/workflows/cicd-main.yml
  README.md
Labels: CI, CI:docs

#1181 feat: Support passing in tool calls with OpenAI chat format when doing SFT
  README.md
  docs/guides/sft.md
  examples/configs/sft.yaml
  examples/run_sft.py
  nemo_rl/algorithms/utils.py
  nemo_rl/data/datasets/response_datasets/__init__.py
  nemo_rl/data/datasets/response_datasets/oai_format_dataset.py
  nemo_rl/data/llm_message_utils.py
  tests/unit/data/datasets/test_preserving_dataset.py
Labels: documentation, CI:L1, r0.4.0

#1215 test: add bisect-script.sh to help bisect CI tests
  tools/bisect-script.sh
Labels: CI:docs

#1138 fix: Reduce memory usage of gradient norm computation
  nemo_rl/models/dtensor/parallelize.py
  tests/unit/models/dtensor/test_parallelize.py
Labels: CI:L1, r0.4.0

#1225 fix: dpo mistral nightly needs more time
  tests/test_suites/llm/dpo-mistral-nemo-instruct-2407-1n8g-fsdp2tp8-actckpt-long.sh
Labels: documentation, CI:L0

#1226 fix: nightlies using v1 can't use model_save_format=safetensors
  examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-8n8g-fsdp2tp8-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-gspo-deepscaler-1.5b-8K.yaml
Labels: CI:L0

#1218 chore: Update cherry-pick workflow to use v0.63.0
  .github/workflows/cherry-pick-release-commit.yml
Labels: CI

#1006 feat: add on policy distillation algorithm
  README.md
  examples/configs/distillation_math.yaml
  examples/configs/recipes/llm/distillation-qwen3-32b-to-1.7b-base-1n8g-fsdp2tp1.v1.yaml
  examples/configs/recipes/llm/distillation-qwen3-32b-to-4b-base-1n8g-fsdp2tp2-dynamicbatch.v1.yaml
  examples/configs/recipes/llm/distillation-qwen3-32b-to-4b-base-2n8g-fsdp2tp2-long.v1.yaml
  examples/configs/recipes/llm/distillation-qwen3-32b-to-4b-base-2n8g-fsdp2tp8-noncolocated.v1.yaml
  examples/configs/recipes/llm/distillation-qwen3-32b-to-4b-instruct-2n8g-fsdp2tp2-seqpack.v1.yaml
  examples/configs/recipes/llm/distillation-qwen3-32b-to-8b-base-2n8g-fsdp2tp2.v1.yaml
  examples/configs/recipes/llm/distillation-qwen3-32b-to-8b-base-4n8g-fsdp2tp8-long.v1.yaml
  examples/run_distillation_math.py
  nemo_rl/algorithms/distillation.py
  nemo_rl/algorithms/loss_functions.py
  nemo_rl/distributed/batched_data_dict.py
  nemo_rl/distributed/model_utils.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/dtensor_policy_worker_v2.py
  nemo_rl/models/policy/interfaces.py
  nemo_rl/models/policy/lm_policy.py
  nemo_rl/models/policy/megatron_policy_worker.py
  tests/functional/L1_Functional_Tests_GPU.sh
  tests/functional/distillation.sh
  tests/test_suites/llm/distillation-qwen3-32b-to-1.7b-base-1n8g-fsdp2tp1.v1.sh
  tests/test_suites/llm/distillation-qwen3-32b-to-4b-base-1n8g-fsdp2tp2-dynamicbatch.v1.sh
  tests/test_suites/llm/distillation-qwen3-32b-to-4b-base-2n8g-fsdp2tp2-long.v1.sh
  tests/test_suites/llm/distillation-qwen3-32b-to-4b-base-2n8g-fsdp2tp8-noncolocated.v1.sh
  tests/test_suites/llm/distillation-qwen3-32b-to-4b-instruct-2n8g-fsdp2tp2-seqpack.v1.sh
  tests/test_suites/llm/distillation-qwen3-32b-to-8b-base-2n8g-fsdp2tp2.v1.sh
  tests/test_suites/llm/distillation-qwen3-32b-to-8b-base-4n8g-fsdp2tp8-long.v1.sh
  tests/test_suites/nightly.txt
  tests/test_suites/release.txt
  tests/unit/algorithms/test_distillation.py
  tests/unit/algorithms/test_loss_functions.py
  tests/unit/distributed/test_batched_data_dict.py
  tests/unit/distributed/test_model_utils.py
  tests/unit/test_config_validation.py
  tests/unit/test_recipes_and_test_suites.py
Labels: algorithm, CI:L1, r0.4.0

#1231 fix: grpo-llama3.1-8b-instruct-1n8g-megatron-fp8-rollouts runs 40 steps
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8-rollouts.v2.yaml
  tests/test_suites/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8-rollouts.v2.sh
  tests/test_suites/nightly.txt
Labels: CI:L0, r0.4.0
