Repository NVIDIA-NeMo/RL, pull requests merged in 2025-06, with the labels that each got.

#460 feat: add vllm pipeline parallelism and multi node rollout
  examples/configs/eval.yaml
  examples/configs/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/grpo_deepscaler-1.5b-24K.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_sliding_puzzle.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  nemo_rl/distributed/virtual_cluster.py
  nemo_rl/distributed/worker_groups.py
  nemo_rl/models/generation/vllm.py
  tests/unit/distributed/test_virtual_cluster.py
  tests/unit/experience/test_rollouts.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/generation/test_vllm_large_model.py
Labels: CI:L0

#292 feat: remove manual refit param
  examples/configs/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_math_8B.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  nemo_rl/algorithms/grpo.py
  nemo_rl/models/policy/__init__.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/fsdp1_policy_worker.py
  nemo_rl/models/policy/hf_policy.py
  nemo_rl/models/policy/interfaces.py
  nemo_rl/utils/nvml.py
  tests/unit/models/generation/test_vllm_generation.py
Labels: CI:L1

#479 ci: Fix GHA template ref after org move
  .github/workflows/build-test-publish-wheel.yml
  .github/workflows/cherry-pick-release-commit.yml
  .github/workflows/cicd-main.yml
  .github/workflows/copyright-check.yml
  .github/workflows/release-freeze.yml
  .github/workflows/release.yaml
  .github/workflows/semantic-pull-request.yml
Labels: CI

#478 fix: async rollouts; incorrect tokens generated
  nemo_rl/experience/rollouts.py
  nemo_rl/models/generation/vllm.py
Labels: CI:L0

#490 ci: Fix tests after base image bump
  .github/workflows/_run_test.yml
  .github/workflows/cicd-main.yml
Labels: CI, CI:L1

#454 fix(chore): bump vllm, TE, ray, torch + more performant cuda base
  .github/workflows/_run_test.yml
  .github/workflows/cicd-main.yml
  README.md
  docker/Dockerfile
  nemo_rl/distributed/virtual_cluster.py
  pyproject.toml
  uv.lock
Labels: CI, CI:L1

#482 feat: using v1 runtime for async rollouts
  docs/model-quirks.md
  nemo_rl/distributed/worker_groups.py
  nemo_rl/models/generation/vllm.py
Labels: documentation, CI:L0

#495 fix: add more checks for seq len as well as a script to check `max_model_len`
  docs/adding-new-models.md
  nemo_rl/experience/rollouts.py
  nemo_rl/models/generation/vllm.py
  tools/model_diagnostics/1.max_model_len_respected.py
Labels: documentation, CI:docs

#489 feat: support non-colocated sync vllm
  .github/workflows/cicd-main.yml
  examples/configs/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  nemo_rl/algorithms/grpo.py
  nemo_rl/distributed/ray_actor_environment_registry.py
  nemo_rl/models/generation/interfaces.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/generation/vllm_backend.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/hf_policy.py
  nemo_rl/models/policy/interfaces.py
  tests/functional/grpo_non_colocated.sh
  tests/unit/experience/test_rollouts.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/generation/test_vllm_large_model.py
  tests/unit/utils/test_native_checkpoint.py
Labels: CI, CI:L1

#511 feat: Moving everything to 'Policy' and lm_policy for Megatron (removing 'hf')
  docs/design-docs/uv.md
  docs/testing.md
  nemo_rl/algorithms/dpo.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/algorithms/sft.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/lm_policy.py
  tests/unit/experience/test_rollouts.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/policy/test_dtensor_worker.py
  tests/unit/models/policy/test_fsdp1_worker.py
  tests/unit/utils/test_native_checkpoint.py
Labels: documentation

#349 feat: async ray monitoring now tracks system memory
  examples/configs/dpo.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_sliding_puzzle.yaml
  examples/configs/sft.yaml
  nemo_rl/utils/logger.py
  tests/functional/dpo.sh
  tests/functional/grpo.sh
  tests/functional/sft.sh
  tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp1.v2.sh
  tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.sh
  tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.sh
  tests/test_suites/llm/sft-llama3.2-1b-1n8g-fsdp2tp1.v2.sh
  tests/test_suites/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.sh
  tests/unit/utils/test_logger.py
Labels: CI:L1

#487 feat: add nsys profiling for for dtensor and vllm workers
  docs/cluster.md
  docs/debugging.md
  docs/index.md
  docs/nsys-profiling.md
  nemo_rl/__init__.py
  nemo_rl/algorithms/dpo.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/algorithms/sft.py
  nemo_rl/distributed/worker_group_utils.py
  nemo_rl/distributed/worker_groups.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/fsdp1_policy_worker.py
  nemo_rl/models/policy/lm_policy.py
  nemo_rl/models/policy/megatron_policy_worker.py
  nemo_rl/utils/nsys.py
  pyproject.toml
  ray.sub
  tests/unit/distributed/test_worker_groups.py
  tests/unit/distributed/test_worker_groups_utils.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/test_nsight_patching.py
  tests/unit/utils/test_nsys.py
  uv.lock
Labels: documentation, CI:L1

#542 fix: increase test timeout 2hr -> 3hr
  .github/workflows/cicd-main.yml
Labels: CI

#506 feat: Multi turn async
  docs/model-quirks.md
  nemo_rl/algorithms/grpo.py
  nemo_rl/distributed/worker_groups.py
  nemo_rl/experience/rollouts.py
  nemo_rl/models/generation/vllm.py
  tests/unit/experience/test_rollouts.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/generation/test_vllm_large_model.py
Labels: documentation, CI:L0

#558 fix: remove reference_model_buffers in fsdp2
  nemo_rl/models/policy/dtensor_policy_worker.py
Labels: CI:docs

#175 feat: Log code in wandb
  nemo_rl/utils/logger.py
Labels: Run CICD

#560 docs: fix some typos on nsys/model-quirk pages
  docs/model-quirks.md
  docs/nsys-profiling.md
Labels: documentation

#502 docs: Add missing arguments to DeepScaler evaluation
  docs/guides/grpo-deepscaler.md
Labels: documentation
