Repository NVIDIA-NeMo/RL, pull requests merged in 2025-05, with the labels that each got.

#406 fix: logging validation samples was broken and not logging anything
  nemo_rl/algorithms/grpo.py
  nemo_rl/data/llm_message_utils.py
  nemo_rl/utils/logger.py
Labels: CI:L0

#321 feat: Total worker isolation (avoid imports of worker deps in base environment)
  .github/workflows/_run_test.yml
  docs/design-docs/uv.md
  examples/run_eval.py
  examples/run_grpo_math.py
  nemo_rl/distributed/ray_actor_environment_registry.py
  nemo_rl/distributed/worker_groups.py
  nemo_rl/environments/games/sliding_puzzle.py
  nemo_rl/environments/math_environment.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/generation/vllm_backend.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/fsdp1_policy_worker.py
  nemo_rl/models/policy/hf_policy.py
  tests/unit/distributed/__init__.py
  tests/unit/distributed/test_worker_groups.py
  tests/unit/environments/test_math_environment.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/test_envs.py
Labels: documentation, CI

#416 fix: Updated hf home cache dir back to the original one (after clean)
  .github/workflows/_run_test.yml
Labels: CI

#240 docs: add instructions for how to use the ray debugger
  docs/assets/ray-debug-step1.png
  docs/assets/ray-debug-step2.png
  docs/assets/ray-debug-step3.png
  docs/assets/ray-debug-step4.png
  docs/debugging.md
  docs/index.md
  ray.sub
Labels: documentation, CI:docs

#414 ci: Update cherry-pick workflow to pass semantic PR check
  .github/workflows/cherry-pick-release-commit.yml
  .github/workflows/semantic-pull-request.yml
Labels: CI

#351 fix: fix refit of FusedMoE
  nemo_rl/algorithms/utils.py
  nemo_rl/models/huggingface/common.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/fsdp1_policy_worker.py
  nemo_rl/models/policy/utils.py
  pyproject.toml
  uv.lock
Labels: CI:L1

#420 fix: fixes #377 to rename md files with _ to -
  .pre-commit-config.yaml
  docs/design-docs/loss-functions.md
  docs/index.md
Labels: documentation

#422 docs: Enable Version Switcher and Analytics Tracker
  docs/conf.py
  docs/documentation.md
  docs/project.json
  docs/versions1.json
Labels: documentation, r0.2.1

#433 cp: `docs: Enable Version Switcher and Analytics Tracker (422)` into `r0.2.1`
  docs/conf.py
  docs/documentation.md
  docs/project.json
  docs/versions1.json
Labels: documentation, Run CICD, cherry-pick

#434 cp: `ci: Update cherry-pick workflow to pass semantic PR check (#414)` into `r0.2.1`
  .github/workflows/cherry-pick-release-commit.yml
  .github/workflows/semantic-pull-request.yml
Labels: CI

#423 ci: Upload codecov
  .github/workflows/cicd-main.yml
  codecov.yml
Labels: CI, CI:L0

#437 ci: Set codecov override_branch to main if from merge queue
  .github/workflows/cicd-main.yml
Labels: CI

#410 feat: parametrize GPUS_PER_NODE and CPUS_PER_WORKER in ray.sub
  docs/cluster.md
  ray.sub
Labels: documentation

#352 feat: general fsdp2 on non-MoE models + HF TP plan
  docs/design-docs/fsdp2-parallel-plan.md
  docs/index.md
  examples/configs/dpo.yaml
  examples/configs/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/grpo_deepscaler-1.5b-24K.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp1-quick.v2.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp2-quick.v2.yaml
  examples/configs/recipes/llm/dpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp1.v2.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.yaml
  examples/configs/recipes/llm/sft-llama3.2-1b-1n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.yaml
  examples/configs/sft.yaml
  examples/configs/sft_openmathinstruct2.yaml
  examples/custom_parallel.py
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/huggingface/common.py
  nemo_rl/models/policy/__init__.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/huggingface/test_common.py
  tests/unit/models/policy/test_dtensor_worker.py
  tests/unit/models/policy/test_fsdp1_worker.py
  tests/unit/utils/test_native_checkpoint.py
Labels: documentation, CI:docs, CI:L1

#459 docs: improve ray debugging instructions
  docs/debugging.md
Labels: documentation

#449 feat: refit speedup
  nemo_rl/distributed/worker_groups.py
  nemo_rl/models/generation/vllm.py
  tests/unit/distributed/test_worker_groups.py
Labels: CI:L1

#461 ci: Update release workflow to optionally release pypi without github release
  .github/workflows/release.yaml
Labels: CI
