Repository NVIDIA-NeMo/RL, pull requests merged in 2025-10, with the labels that each got.

#1229 fix: fix checkpointing when `val_period` does not divide `save_period`
  nemo_rl/algorithms/dpo.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/algorithms/sft.py
  nemo_rl/utils/checkpoint.py
  tests/unit/utils/test_checkpoint.py
Labels: CI:L1

#1239 fix: lower steps in smolvlm nightly test
  examples/configs/recipes/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v2.yaml.disabled
  tests/test_suites/nightly.txt
  tests/test_suites/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v2.sh.disabled
Labels: CI:L0

#1147 fix: Release gradient memory after policy training
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/dtensor_policy_worker_v2.py
Labels: CI:L1, r0.4.0

#1233 fix: fp8 rollout nightly fix check from step 100 to 40
  tests/test_suites/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8-rollouts.v2.sh
Labels: CI:docs

#1257 fix: moonlight CI test mem regression (increase cache flush)
  examples/configs/recipes/llm/grpo-moonlight-16ba3b-4n8g-megatron.yaml
Labels: CI:L0, r0.4.0

#1237 docs: add missing async_grpo.enabled flag to configuration
  docs/guides/async-grpo.md
Labels: documentation, CI:docs, asyncRL, r0.4.0

#1269 docs: Update v0.3.0 announcement link
  README.md
Labels: CI:docs

#1249 feat: add valid_tokens_per_sec metric and total_valid_tokens to save state
  nemo_rl/algorithms/distillation.py
  nemo_rl/algorithms/dpo.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/algorithms/rm.py
  nemo_rl/algorithms/sft.py
  tests/unit/algorithms/test_distillation.py
  tests/unit/algorithms/test_rm.py
  tests/unit/algorithms/test_sft.py
Labels: CI:L1, r0.4.0

#1272 fix: remove noisy qwen2 vl nightly test loss check
  tests/test_suites/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.sh
Labels: CI:L0, r0.4.0

#1273 fix: colocated.resources.gpus_per_node is now required for colocated setups
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-2n8g-fsdp2tp1-noncolocated.yaml
  nemo_rl/algorithms/distillation.py
  nemo_rl/algorithms/grpo.py
  tests/unit/algorithms/test_distillation.py
  tests/unit/algorithms/test_grpo.py
Labels: CI:L1, r0.4.0

#1284 chore: 0.4.0.rc0 -> 0.5.0.rc0
  nemo_rl/package_info.py
Labels: CI:docs

#1285 chore: 0.4.0.rc0 -> 0.4.0
  nemo_rl/package_info.py
Labels: CI:docs

#1297 chore: 0.4.0.rc0 -> 0.4.0
  nemo_rl/package_info.py
Labels: CI:docs

#1120 fix: parallel state initialization error in Megatron to HF model conversion
  nemo_rl/models/megatron/community_import.py
Labels: CI:L1, external, community-request, x-inflection, r0.4.0

#1280 fix: deepscaler-24k test reduce to 10 steps to safely finish in 4 hr
  tests/test_suites/llm/grpo-deepscaler-1.5b-24K.sh
Labels: CI:docs, r0.4.0

#1271 fix: qwen32 nightly metric check more stable
  tests/test_suites/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v3.sh
Labels: CI:L1, r0.4.0

#1305 feat: Add deepseek flops tracker (original #1250)
  nemo_rl/utils/flops_tracker.py
  tests/unit/utils/test_flops_counter.py
Labels: CI:L1, r0.4.0

#1264 fix: enhancing non-colocated refit performance by having inclusive comm group
  nemo_rl/algorithms/distillation.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/models/generation/vllm/vllm_backend.py
  nemo_rl/models/generation/vllm/vllm_generation.py
  nemo_rl/models/generation/vllm/vllm_worker.py
  nemo_rl/models/generation/vllm/vllm_worker_async.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/dtensor_policy_worker_v2.py
  nemo_rl/models/policy/interfaces.py
  nemo_rl/models/policy/lm_policy.py
  nemo_rl/models/policy/megatron_policy_worker.py
  tests/unit/algorithms/test_distillation.py
  tests/unit/models/generation/test_vllm_generation.py
Labels: Performance, CI:L1, r0.4.0
