Repository NVIDIA-NeMo/RL, pull requests merged in 2025-08, with the labels that each got.

#810 docs: add a section on our config design
  docs/design-docs/design-and-philosophy.md
Labels: documentation

#825 chore: 0.3.0 -> 0.3.1
  docs/versions1.json
  nemo_rl/package_info.py
Labels: documentation

#617 ci: Refactor unit tests to run in concurrent jobs
  .github/actions/test-template/action.yml
  .github/copy-pr-bot.yml
  .github/workflows/_run_test.yml
  .github/workflows/cicd-main.yml
  tests/docs/Docs_Tests.sh
  tests/functional/L1_Functional_Tests_GPU.sh
  tests/functional/dpo.sh
  tests/functional/eval.sh
  tests/functional/eval_async.sh
  tests/functional/grpo.sh
  tests/functional/grpo_megatron.sh
  tests/functional/grpo_multiturn.sh
  tests/functional/grpo_non_colocated.sh
  tests/functional/rm.sh
  tests/functional/sft.sh
  tests/functional/test_mcore_extra_installed_correctly.sh
  tests/run_unit.sh
  tests/unit/L0_Unit_Tests_Generation.sh
  tests/unit/L0_Unit_Tests_Other.sh
  tests/unit/L0_Unit_Tests_Policy.sh
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/policy/test_dtensor_worker.py
Labels: CI, CI:L1

#640 feat: implement cons@k evaluation
  docs/guides/eval.md
  examples/configs/evals/eval.yaml
  nemo_rl/environments/code_environment.py
  nemo_rl/environments/games/sliding_puzzle.py
  nemo_rl/environments/interfaces.py
  nemo_rl/environments/math_environment.py
  nemo_rl/environments/tools/retriever.py
  nemo_rl/evals/eval.py
  nemo_rl/experience/rollouts.py
  tests/unit/algorithms/test_grpo.py
  tests/unit/evals/test_eval.py
  tests/unit/test_envs.py
Labels: documentation, CI:L0

#857 fix: force use of eager (disabled cuda graphs) due to convergence issues
  docs/model-quirks.md
  examples/configs/grpo-deepscaler-1.5b-24K.yaml
  examples/configs/grpo-deepscaler-1.5b-8K.yaml
Labels: documentation

#613 feat: support non-colocated in mcore
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/generation/vllm_backend.py
  nemo_rl/models/policy/megatron_policy_worker.py
  pyproject.toml
  tests/unit/models/generation/test_vllm_generation.py
  uv.lock
Labels: CI:L1

#837 docs: Link uv's installation instructions to uv's website
  .pre-commit-config.yaml
  README.md
  docs/conf.py
Labels: documentation

#700 fix: remove tie weight check
  docs/model-quirks.md
  examples/configs/grpo_math_1B.yaml
  examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/huggingface/common.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/generation/test_vllm_large_model.py
  tests/unit/models/huggingface/test_common.py
  tests/unit/models/policy/test_dtensor_worker.py
  tests/unit/models/policy/test_megatron_worker.py
  tests/unit/utils/test_native_checkpoint.py
Labels: documentation, CI:L0

#481 feat: add nemotron5 sharding
  docs/testing.md
  nemo_rl/distributed/virtual_cluster.py
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  pyproject.toml
  tests/unit/L0_Unit_Tests_Generation.sh
  tests/unit/L0_Unit_Tests_Other.sh
  tests/unit/L0_Unit_Tests_Policy.sh
  tests/unit/conftest.py
  tests/unit/models/policy/test_dtensor_worker.py
  tests/unit/prepare_unit_test_assets.py
  uv.lock
Labels: documentation, CI:L0, research

#879 feat: Add TP to embed_tokens and lm_head for Gemma models
  nemo_rl/models/dtensor/parallelize.py
Labels: CI:L1

#900 refactor: split sync/async vllm worker ([1/2] of refactor vllm worker)
  docs/design-docs/generation.md
  docs/guides/grpo.md
  nemo_rl/distributed/ray_actor_environment_registry.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/generation/vllm/__init__.py
  nemo_rl/models/generation/vllm/config.py
  nemo_rl/models/generation/vllm/vllm_backend.py
  nemo_rl/models/generation/vllm/vllm_generation.py
  nemo_rl/models/generation/vllm/vllm_worker.py
  nemo_rl/models/generation/vllm/vllm_worker_async.py
  pyrefly.toml
Labels: documentation, CI:docs

#712 feat: GRPO + SFT Dtensor support for multimodal training
  .github/actions/test-template/action.yml
  examples/configs/recipes/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/recipes/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/rm.yaml
  examples/configs/sft_vlm_3B.yaml
  examples/configs/vlm_grpo_3B.yaml
  examples/prompts/clevr_cogent_cot.txt
  examples/prompts/geo3k.txt
  examples/prompts/refcoco.txt
  examples/run_sft.py
  examples/run_vlm_grpo.py
  examples/run_vlm_sft.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/algorithms/sft.py
  nemo_rl/algorithms/utils.py
  nemo_rl/data/__init__.py
  nemo_rl/data/datasets.py
  nemo_rl/data/hf_datasets/__init__.py
  nemo_rl/data/hf_datasets/clevr.py
  nemo_rl/data/hf_datasets/geometry3k.py
  nemo_rl/data/hf_datasets/refcoco.py
  nemo_rl/data/llm_message_utils.py
  nemo_rl/data/multimodal_utils.py
  nemo_rl/distributed/batched_data_dict.py
  nemo_rl/distributed/ray_actor_environment_registry.py
  nemo_rl/environments/rewards.py
  nemo_rl/environments/vlm_environment.py
  nemo_rl/experience/rollouts.py
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/generation/vllm/utils.py
  nemo_rl/models/generation/vllm/vllm_worker.py
  nemo_rl/models/generation/vllm/vllm_worker_async.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/lm_policy.py
  nemo_rl/models/policy/utils.py
  nemo_rl/utils/native_checkpoint.py
  pyproject.toml
  pyrefly.toml
  tests/functional/L1_Functional_Tests_GPU.sh
  tests/functional/vlm_grpo.sh
  tests/test_suites/nightly.txt
  tests/test_suites/vlm/common.env
  tests/test_suites/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.sh
  tests/test_suites/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v1.sh
  tests/unit/data/test_llm_message_utils.py
  tests/unit/data/test_multimodal_dict.py
  tests/unit/distributed/test_batched_data_dict.py
  tests/unit/rewards/test_rewards.py
  tests/unit/test_recipes_and_test_suites.py
  uv.lock
Labels: CI, CI:L1

#804 feat: Add recipe to reproduce Tulu-3 DPO model
  examples/configs/recipes/llm/dpo-llama3.1-8b-tulu3-1n8g-fsdp2tp1.yaml
  examples/run_dpo.py
  nemo_rl/data/hf_datasets/__init__.py
  nemo_rl/data/hf_datasets/tulu3.py
  pyrefly.toml
  tests/test_suites/llm/dpo-llama3.1-8b-tulu3-1n8g-fsdp2tp1.sh
  tests/test_suites/release.txt
Labels: community-request

#543 feat: fp8 block scaling
  docs/assets/fp8_curves.png
  docs/fp8.md
  docs/index.md
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_math_8B_megatron_fp8.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8.yaml
  nemo_rl/algorithms/grpo.py
  nemo_rl/models/generation/fp8.py
  nemo_rl/models/generation/vllm/vllm_backend.py
  nemo_rl/models/generation/vllm/vllm_worker.py
  pyproject.toml
  tests/test_suites/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8.sh
  tests/test_suites/nightly.txt
  tests/unit/models/generation/test_vllm_generation.py
  uv.lock
Labels: documentation, CI:L1

#981 fix: Update Automodel integration check logic and message.
  .github/workflows/_automodel_integration_check.yml
Labels: CI

#968 chore: ray-sub - improve robustness
  ray.sub
Labels: external, x-inflection

#926 fix: memory optimizations for Nemotron12B 12k seqlen DPO training
  README.md
  examples/configs/dpo.yaml
  examples/configs/recipes/llm/dpo-mistral-nemo-instruct-2407-1n8g-fsdp2tp8-actckpt-long.yaml
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/policy/__init__.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/dtensor_policy_worker_v2.py
  nemo_rl/models/policy/megatron_policy_worker.py
  nemo_rl/models/policy/utils.py
  nemo_rl/utils/logger.py
  tests/test_suites/llm/dpo-mistral-nemo-instruct-2407-1n8g-fsdp2tp8-actckpt-long.sh
  tests/test_suites/nightly.txt
  tests/unit/models/policy/test_utils.py
Labels: CI:L1

#935 fix: fix temperature-related issues
  nemo_rl/models/generation/vllm/vllm_generation.py
  nemo_rl/models/generation/vllm/vllm_worker.py
  nemo_rl/models/megatron/common.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/dtensor_policy_worker_v2.py
  nemo_rl/models/policy/megatron_policy_worker.py
  tests/unit/models/generation/test_vllm_generation.py
Labels: CI:L1

#997 feat: add vllm enable_expert_parallel
  examples/configs/evals/eval.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_sliding_puzzle.yaml
  examples/configs/recipes/llm/grpo-deepscaler-1.5b-24K.yaml
  examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-gspo-deepscaler-1.5b-8K.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-megatron.yaml
  examples/configs/recipes/llm/grpo-math-qwen3-30ba3b-megatron-tp4-32k.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-megatron.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/recipes/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml
  examples/configs/vlm_grpo_3B.yaml
  nemo_rl/models/generation/vllm/config.py
  nemo_rl/models/generation/vllm/vllm_worker.py
  tests/unit/environments/test_code_environment.py
  tests/unit/environments/test_retriever.py
  tests/unit/experience/test_rollouts.py
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/models/generation/test_vllm_large_model.py
Labels: CI:L1

#931 ci: Update community bot to add issues to shared project
  .github/workflows/community-bot.yml
Labels: CI

#673 feat: preference datasets
  docs/guides/dpo.md
  docs/guides/rm.md
  examples/configs/dpo.yaml
  examples/configs/rm.yaml
  examples/run_dpo.py
  examples/run_rm.py
  nemo_rl/algorithms/dpo.py
  nemo_rl/algorithms/rm.py
  nemo_rl/data/__init__.py
  nemo_rl/data/datasets.py
  nemo_rl/data/hf_datasets/__init__.py
  nemo_rl/data/hf_datasets/dpo.py
  nemo_rl/data/hf_datasets/helpsteer3.py
  nemo_rl/data/hf_datasets/preference_dataset.py
  nemo_rl/data/hf_datasets/tulu3.py
  pyrefly.toml
  tests/unit/data/hf_datasets/test_dpo_dataset.py
  tests/unit/data/hf_datasets/test_helpsteer.py
  tests/unit/data/hf_datasets/test_preference_dataset.py
  tests/unit/data/hf_datasets/test_tulu3.py
  tests/unit/data/test_datasets.py
Labels: documentation, enhancement, training, algorithm

#1001 feat: Fix nsight profiling file sync for multi-node jobs
  docs/nsys-profiling.md
  ray.sub
Labels: documentation
