Repository NVIDIA-NeMo/RL, pull requests merged in 2025-07, with the labels that each got.

#539 feat: improve worker group args/kwargs
  nemo_rl/distributed/worker_groups.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/lm_policy.py
  tests/unit/distributed/test_worker_groups.py
Labels: CI:L1

#512 chore: Update github url after org transfer
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/adding-new-models.md
  docs/model-quirks.md
  examples/configs/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_sliding_puzzle.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/converters/convert_dcp_to_hf.py
  nemo_rl/algorithms/dpo.py
  nemo_rl/distributed/ray_actor_environment_registry.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/fsdp1_policy_worker.py
  nemo_rl/package_info.py
  nemo_rl/utils/native_checkpoint.py
  pyproject.toml
  tests/functional/dpo.sh
  tests/functional/test_converter_roundtrip.py
  tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.sh
  tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.sh
  tests/test_suites/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.sh
  tests/unit/models/generation/test_vllm_generation.py
  tests/unit/utils/test_native_checkpoint.py
  uv.lock
Labels: documentation, CI, CI:docs

#544 fix: load HF model only on rank 0
  examples/configs/eval.yaml
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  tests/unit/models/policy/test_dtensor_worker.py
Labels: CI:L0

#559 feat: supports evaluation of multiple-choice benchmarks
  README.md
  docs/guides/eval.md
  docs/guides/grpo.md
  docs/guides/sft-openmathinstruct2.md
  examples/configs/evals/eval.yaml
  examples/configs/evals/gpqa_eval.yaml
  examples/configs/evals/local_eval.yaml
  examples/configs/evals/math_eval.yaml
  examples/prompts/gpqa.txt
  examples/prompts/mmlu.txt
  examples/run_eval.py
  examples/run_grpo_math.py
  nemo_rl/data/eval_datasets/__init__.py
  nemo_rl/data/eval_datasets/aime2024.py
  nemo_rl/data/eval_datasets/gpqa.py
  nemo_rl/data/eval_datasets/local_math_dataset.py
  nemo_rl/data/eval_datasets/math.py
  nemo_rl/data/eval_datasets/mmlu.py
  nemo_rl/data/eval_datasets/mmlu_pro.py
  nemo_rl/data/processors.py
  nemo_rl/environments/math_environment.py
  nemo_rl/evals/answer_parsing.py
  tests/functional/test_converter_roundtrip.py
  tests/unit/data/eval_datasets/test_gpqa.py
  tests/unit/data/eval_datasets/test_math.py
  tests/unit/data/eval_datasets/test_mmlu.py
  tests/unit/data/test_data_processor.py
  tests/unit/environments/test_math_environment.py
Labels: documentation

#594 fix: enable expandable segments for hopper+
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/megatron_policy_worker.py
  nemo_rl/models/policy/utils.py
Labels: CI:L0

#505 docs: Update guide to include minimum compute requirement
  docs/guides/grpo-deepscaler.md
Labels: documentation

#528 feat: optimize get logprobs when cp enabled.
  nemo_rl/algorithms/loss_functions.py
  nemo_rl/distributed/model_utils.py
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/megatron_policy_worker.py
Labels: CI:L1

#589 feat: Refit: reduce the number of IPC calls by packing weights
  nemo_rl/models/generation/vllm_backend.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/fsdp1_policy_worker.py
  nemo_rl/models/policy/megatron_policy_worker.py
Labels: CI:L0

#624 chore: exclude ray.remote from coverage
  .github/workflows/cicd-main.yml
  nemo_rl/distributed/virtual_cluster.py
  nemo_rl/environments/games/sliding_puzzle.py
  nemo_rl/environments/math_environment.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/megatron_policy_worker.py
  nemo_rl/utils/venvs.py
Labels: CI, CI:L0

#529 feat: guide to configure custom vllm version
  .gitignore
  docs/guides/use-custom-vllm.md
  docs/index.md
  tools/build-custom-vllm.sh
Labels: documentation

#527 fix: Mcore: Added functional grpo test and typing fixes
  .github/workflows/cicd-main.yml
  docs/design-docs/logger.md
  docs/design-docs/loss-functions.md
  docs/guides/grpo.md
  examples/configs/grpo_math_1B_megatron.yaml
  examples/configs/grpo_math_70B_megatron.yaml
  examples/configs/grpo_math_8B_megatron.yaml
  nemo_rl/algorithms/grpo.py
  nemo_rl/distributed/batched_data_dict.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  tests/functional/grpo_megatron.sh
Labels: documentation, CI

#631 feat: plumb environment variables to RayWorkerGroup
  nemo_rl/distributed/worker_groups.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/lm_policy.py
  nemo_rl/models/policy/megatron_policy_worker.py
  nemo_rl/models/policy/utils.py
  tests/unit/algorithms/__init__.py
  tests/unit/distributed/test_worker_groups.py
  tests/unit/models/__init__.py
  tests/unit/models/policy/test_utils.py
Labels: CI:docs

#347 feat: add script to redact hparam paths from tensorboard logs
  tests/unit/tools/test_copy_tbevent_maybe_redact.py
  tools/__init__.py
  tools/copy_tbevent_maybe_redact.py
  tools/package_release_runs.sh
Labels: CI:L0

#669 docs: Add GitHub icon and link to top bar
  docs/conf.py
  docs/project.json
Labels: documentation

#634 feat: optimize refit by reducing set of IPC handles sent to each device
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/generation/vllm_backend.py
Labels: r0.3.0

#665 feat: introduce megatron checkpoint dir precedence
  docs/design-docs/training-backends.md
  nemo_rl/models/policy/megatron_policy_worker.py
  nemo_rl/models/policy/utils.py
  tests/unit/models/policy/test_utils.py
Labels: documentation, r0.3.0

#681 fix: make mcore lr scheduler configuration consistent with dtensor
  examples/configs/grpo_math_1B_megatron.yaml
  examples/configs/grpo_math_70B_megatron.yaml
  examples/configs/grpo_math_qwen30ba3b_megatron.yaml
  nemo_rl/models/policy/megatron_policy_worker.py
  tests/unit/models/policy/test_megatron_worker.py
Labels: r0.3.0

#678 feat: Enable CP during get_logprobs for dtensor worker.
  docs/model-quirks.md
  nemo_rl/distributed/batched_data_dict.py
  nemo_rl/distributed/model_utils.py
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/huggingface/common.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/lm_policy.py
Labels: documentation, CI:L1

#676 fix: Fix gemma models broken by HF update
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/generation/vllm_backend.py
  tests/unit/models/dtensor/test_parallelize.py
Labels: r0.3.0, CI:L0

#689 chore: add CP+SP (sequence parallel) assertion in DTensor worker
  docs/model-quirks.md
  nemo_rl/models/policy/dtensor_policy_worker.py
  tests/unit/models/policy/test_dtensor_worker.py
Labels: documentation, CI:L0

#697 feat: MLFlow Integration for experiment tracking
  docs/design-docs/logger.md
  examples/configs/dpo.yaml
  examples/configs/grpo-deepscaler-1.5b-8K.yaml
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_math_1B_megatron.yaml
  examples/configs/grpo_sliding_puzzle.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp2-quick.v2.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatron.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatrontp2pp2-quick.yaml
  examples/configs/recipes/llm/dpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml
  examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml
  examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml
  examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt-long.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml
  examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-megatron.yaml
  examples/configs/recipes/llm/sft-llama3.2-1b-1n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.yaml
  examples/configs/sft.yaml
  examples/configs/sft_openmathinstruct2.yaml
  nemo_rl/utils/logger.py
  pyproject.toml
  tests/unit/utils/test_logger.py
  uv.lock
Labels: documentation, CI:L1

#710 chore: Bump 0.2.1 -> 0.3.0
  README.md
  docs/versions1.json
  nemo_rl/package_info.py
Labels: documentation

#695 ci: add a job that checks if submodules are fast forwarded
  .github/workflows/_submodule_check.yml
  .github/workflows/cicd-main.yml
Labels: CI

#726 cp: `fix: unset TP and PP in sft 1 GPU config (717)` into `r0.3.0`
  examples/configs/sft.yaml
Labels: Run CICD, cherry-pick

#735 cp: `fix: guard DPO against dynamic batching and sequence packing (730)` into `r0.3.0`
  nemo_rl/algorithms/dpo.py
Labels: Run CICD, cherry-pick

#737 cp: `docs: Update docs to include submodule instructions (725)` into `r0.3.0`
  docs/design-docs/training-backends.md
Labels: documentation, Run CICD, cherry-pick

#714 fix: Use the conditional temperature scaling in get_logprobs as well
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/utils.py
Labels: r0.3.0

#729 docs: Added docs for sequence packing and dynamic batching
  README.md
  docs/design-docs/sequence-packing-and-dynamic-batching.md
  docs/guides/grpo.md
  docs/index.md
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_math_1B_megatron.yaml
Labels: documentation, r0.3.0, CI:docs

#750 fix: Disable sequence packing in qwen moe config to prevent hang
  examples/configs/grpo_math_qwen30ba3b_megatron.yaml
Labels: r0.3.0

#753 cp: `docs: Added docs for sequence packing and dynamic batching (729)` into `r0.3.0`
  README.md
  docs/design-docs/sequence-packing-and-dynamic-batching.md
  docs/guides/grpo.md
  docs/index.md
  examples/configs/grpo_math_1B.yaml
  examples/configs/grpo_math_1B_megatron.yaml
Labels: documentation, Run CICD, cherry-pick

#738 docs: fix frontpage outdated eval docs
  README.md
  docs/guides/eval.md
Labels: documentation, r0.3.0

#756 cp: `docs: fix frontpage outdated eval docs (738)` into `r0.3.0`
  README.md
  docs/guides/eval.md
Labels: documentation, Run CICD, cherry-pick

#757 ci: Fix community bot
  .github/workflows/community-bot.yml
Labels: CI

#748 fix: Enforce minimum packed sequence bin count and multiple of bin count
  nemo_rl/data/packing/algorithms.py
  nemo_rl/distributed/batched_data_dict.py
  tests/unit/data/packing/test_algorithms.py
  tests/unit/distributed/test_batched_data_dict.py
Labels: community-request, r0.3.1

#759 cp: `fix: Enforce minimum packed sequence bin count and multiple of bin count (748)` into `r0.3.1`
  nemo_rl/data/packing/algorithms.py
  nemo_rl/distributed/batched_data_dict.py
  tests/unit/data/packing/test_algorithms.py
  tests/unit/distributed/test_batched_data_dict.py
Labels: Run CICD, cherry-pick

#761 feat: avoid softmax deepcopy in logprobs (tpoisonooo)
  nemo_rl/distributed/model_utils.py
  tests/unit/distributed/test_model_utils.py
Labels: r0.3.1

#763 cp: `feat: avoid softmax deepcopy in logprobs (tpoisonooo) (761)` into `r0.3.1`
  nemo_rl/distributed/model_utils.py
  tests/unit/distributed/test_model_utils.py
Labels: Run CICD, cherry-pick

#675 chore: switch from mypy to pyrefly
  .github/workflows/cicd-main.yml
  .pre-commit-config.yaml
  examples/configs/dpo.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp2-quick.v2.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatron.yaml
  examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatrontp2pp2-quick.yaml
  examples/configs/recipes/llm/dpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.yaml
  examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-megatron.yaml
  examples/configs/recipes/llm/sft-llama3.2-1b-1n8g-fsdp2tp1.v2.yaml
  examples/configs/recipes/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.yaml
  examples/configs/sft.yaml
  examples/configs/sft_openmathinstruct2.yaml
  examples/run_grpo_sliding_puzzle.py
  mypy.ini
  nemo_rl/algorithms/dpo.py
  nemo_rl/algorithms/grpo.py
  nemo_rl/algorithms/interfaces.py
  nemo_rl/algorithms/sft.py
  nemo_rl/algorithms/utils.py
  nemo_rl/data/datasets.py
  nemo_rl/data/hf_datasets/oai_format_dataset.py
  nemo_rl/data/interfaces.py
  nemo_rl/distributed/batched_data_dict.py
  nemo_rl/distributed/collectives.py
  nemo_rl/distributed/model_utils.py
  nemo_rl/distributed/named_sharding.py
  nemo_rl/distributed/virtual_cluster.py
  nemo_rl/environments/games/sliding_puzzle.py
  nemo_rl/environments/interfaces.py
  nemo_rl/environments/math_environment.py
  nemo_rl/evals/eval.py
  nemo_rl/experience/rollouts.py
  nemo_rl/models/dtensor/parallelize.py
  nemo_rl/models/generation/interfaces.py
  nemo_rl/models/generation/vllm.py
  nemo_rl/models/generation/vllm_backend.py
  nemo_rl/models/megatron/converters/common.py
  nemo_rl/models/megatron/converters/deepseek.py
  nemo_rl/models/megatron/refit_utils.py
  nemo_rl/models/policy/__init__.py
  nemo_rl/models/policy/interfaces.py
  nemo_rl/models/policy/megatron_policy_worker.py
  nemo_rl/utils/checkpoint.py
  nemo_rl/utils/config.py
  nemo_rl/utils/logger.py
  pyproject.toml
  pyrefly.toml
  tools/find_available_port_ranges.py
  tools/model_diagnostics/2.long_generation_decode_vs_prefill.py
  uv.lock
Labels: CI, CI:L0

#764 docs: update nsys docs to remove vllm which requires a different profiling mechanism
  docs/nsys-profiling.md
Labels: documentation

#609 feat: adding support for Bradley-Terry reward model training
  .github/workflows/cicd-main.yml
  README.md
  docs/guides/rm.md
  docs/index.md
  examples/configs/rm.yaml
  examples/run_rm.py
  nemo_rl/algorithms/loss_functions.py
  nemo_rl/algorithms/rm.py
  nemo_rl/data/datasets.py
  nemo_rl/models/policy/__init__.py
  nemo_rl/models/policy/dtensor_policy_worker.py
  nemo_rl/models/policy/megatron_policy_worker.py
  tests/functional/rm.sh
  tests/unit/algorithms/test_rm.py
Labels: documentation, enhancement, CI, training, algorithm

#322 feat: code execution & tool use
  .gitignore
  nemo_rl/distributed/ray_actor_environment_registry.py
  nemo_rl/environments/code_environment.py
  nemo_rl/environments/tools/retriever.py
  nemo_rl/experience/rollouts.py
  tests/unit/environments/test_code_environment.py
  tests/unit/environments/test_retriever.py
Labels: CI:L0

#777 feat: add AIME-2025 eval dataset.
  docs/guides/eval.md
  nemo_rl/data/eval_datasets/__init__.py
  nemo_rl/data/eval_datasets/aime2025.py
  pyrefly.toml
Labels: documentation, community-request

#806 docs: documentation and unit test for env var precedence
  docs/design-docs/env-vars.md
  docs/index.md
  tests/unit/distributed/test_worker_groups.py
Labels: documentation
